development:
  adapter: postgresql
  database: development
  username: postgres
  password: Kjera6738

test:
  adapter: postgresql
  database: test
  username: postgres
  password: Kjera6738

production:
  adapter: postgresql
  database: production
  username: postgres
  password: Kjera6738