development:
  adapter: postgresql
  database: development
  host: localhost
  pool: 20

test:
  adapter: postgresql
  database: test
  host: localhost
  pool: 20

production:
  adapter: postgresql
  database: production
  host: localhost
  pool: 20