development:
  adapter: postgresql
  database: development
  host: localhost
  pool: 10

test:
  adapter: postgresql
  database: test
  host: localhost
  pool: 10

production:
  adapter: postgresql
  database: production
  host: localhost
  pool: 10