development:
  adapter: postgresql
  database: development
  username: schoolsupport
  password: shoob2420
  pool: 10

test:
  adapter: postgresql
  database: test
  username: schoolsupport
  password: shoob2420
  pool: 10

production:
  adapter: postgresql
  database: production
  username: schoolsupport
  password: shoob2420
  pool: 10